// Generated by scripts/gen_types.py -- do not edit by hand.
//
// CI regenerates this and fails on a diff, so the wire contract cannot drift
// between the Python payload models and the client that reads them.


export type SseEventName = "meta" | "token" | "thinking" | "tool_call_start" | "tool_call_end" | "chart" | "error" | "done";

export interface UsagePayload {
  input_tokens?: number;
  output_tokens?: number;
  cache_read_input_tokens?: number;
}

export interface MetaPayload {
  seq: number;
  conversation_id: string;
  message_id: string;
  role: string;
  tenant_id: number | null;
  model_backend: string;
  catalog_version: string;
  demo_mode: boolean;
}

export interface TokenPayload {
  seq: number;
  text: string;
}

export interface ThinkingPayload {
  seq: number;
  text: string;
}

export interface ToolCallStartPayload {
  seq: number;
  call_id: string;
  tool: string;
  args: Record<string, unknown>;
  turn: number;
}

export interface ToolCallEndPayload {
  seq: number;
  call_id: string;
  tool: string;
  ok: boolean;
  duration_ms: number;
  row_count?: number;
  truncated?: boolean;
  result_id?: string;
  sql?: string;
  error_code?: string;
  message?: string;
  notes?: string[];
}

export interface ChartPayload {
  seq: number;
  chart_id: string;
  call_id: string;
  spec: Record<string, unknown>;
  columns: Record<string, string>[];
  rows: unknown[][];
}

export interface ErrorPayload {
  seq: number;
  code: string;
  message: string;
  fatal: boolean;
}

export interface DonePayload {
  seq: number;
  message_id: string;
  stop_reason: string;
  turns: number;
  total_duration_ms: number;
  usage: UsagePayload;
}

export type SseEvent =
  | { event: "meta"; data: MetaPayload }
  | { event: "token"; data: TokenPayload }
  | { event: "thinking"; data: ThinkingPayload }
  | { event: "tool_call_start"; data: ToolCallStartPayload }
  | { event: "tool_call_end"; data: ToolCallEndPayload }
  | { event: "chart"; data: ChartPayload }
  | { event: "error"; data: ErrorPayload }
  | { event: "done"; data: DonePayload };
