"""Generate the frontend's SSE types from the Pydantic payload models.

CI runs this and then `git diff --exit-code`, so a backend payload change that
is not mirrored fails the build rather than becoming an undefined field at
runtime in the trace panel.

Deliberately a small hand-rolled emitter rather than a JSON-Schema-to-TypeScript
dependency: the payload models are simple, the output is meant to be read in
review, and the whole point is that a change here is obvious in a diff.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, get_args, get_origin

from pydantic import BaseModel
from pydantic.fields import FieldInfo

from ledger.api.sse import ALL_PAYLOADS, EventName
from ledger.logging import configure_logging, get_logger

log = get_logger(__name__)

OUTPUT = Path(__file__).resolve().parents[1] / "web" / "src" / "api" / "types.ts"

HEADER = """\
// Generated by scripts/gen_types.py -- do not edit by hand.
//
// CI regenerates this and fails on a diff, so the wire contract cannot drift
// between the Python payload models and the client that reads them.

"""

_PRIMITIVES: dict[Any, str] = {
    str: "string",
    int: "number",
    float: "number",
    bool: "boolean",
    type(None): "null",
}


def ts_type(annotation: Any) -> str:
    if annotation in _PRIMITIVES:
        return _PRIMITIVES[annotation]

    origin = get_origin(annotation)
    args = get_args(annotation)

    if origin is None:
        if isinstance(annotation, type) and issubclass(annotation, BaseModel):
            return annotation.__name__
        return "unknown"

    if origin is list:
        return f"{ts_type(args[0])}[]"
    if origin is dict:
        return f"Record<string, {ts_type(args[1])}>"

    # Literal["a", "b"] and unions, including `X | None`.
    rendered = []
    for arg in args:
        if isinstance(arg, str):
            rendered.append(f'"{arg}"')
        else:
            rendered.append(ts_type(arg))
    unique = list(dict.fromkeys(rendered))
    return " | ".join(unique)


def field_line(name: str, field: FieldInfo) -> str:
    rendered = ts_type(field.annotation)
    optional = "" if field.is_required() else "?"
    # `X | null` plus an optional marker is noise; keep one or the other.
    if optional and rendered.endswith(" | null"):
        rendered = rendered.removesuffix(" | null")
    return f"  {name}{optional}: {rendered};"


def render_interface(model: type[BaseModel]) -> str:
    lines = [f"export interface {model.__name__} {{"]
    lines += [field_line(name, field) for name, field in model.model_fields.items()]
    lines.append("}")
    return "\n".join(lines)


def render() -> str:
    parts: list[str] = [HEADER]

    names = " | ".join(f'"{name}"' for name in get_args(EventName))
    parts.append(f"export type SseEventName = {names};\n")

    # Nested models referenced by a payload, emitted first.
    seen: set[type[BaseModel]] = set()
    nested: list[type[BaseModel]] = []
    for model in ALL_PAYLOADS:
        for field in model.model_fields.values():
            annotation = field.annotation
            if (
                isinstance(annotation, type)
                and issubclass(annotation, BaseModel)
                and annotation not in seen
            ):
                seen.add(annotation)
                nested.append(annotation)

    parts += [render_interface(model) + "\n" for model in nested]
    parts += [render_interface(model) + "\n" for model in ALL_PAYLOADS]

    union = "\n".join(
        f'  | {{ event: "{name}"; data: {model.__name__} }}'
        for name, model in zip(get_args(EventName), ALL_PAYLOADS, strict=True)
    )
    parts.append(f"export type SseEvent =\n{union};\n")

    return "\n".join(parts)


def main() -> int:
    configure_logging()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render())
    log.info("wrote %s", OUTPUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
