"""The role-scoped catalogue, served directly.

This is the same `ScopedCatalog` the tool layer is handed, rendered for a
person instead of for a model. Two reasons it is worth an endpoint:

* Asking "what can I ask about" through `list_columns` spends a model turn to
  answer a question the server already knows, and costs money to do it.
* A viewer's catalogue is visibly shorter than an analyst's, so the access
  boundary is something you can see rather than something you have to take on
  trust or discover by being refused.

`scope_catalog` remains the only producer of a scoped catalogue, so this route
cannot show a column the tool layer would hide -- the two cannot drift, because
there is only one of them.
"""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter
from pydantic import BaseModel

from ledger.api.deps import PrincipalDep, StateDep
from ledger.catalog.scope import scope_catalog

router = APIRouter(tags=["catalog"])


class CatalogColumn(BaseModel):
    name: str
    type: str
    semantic_type: str
    description: str | None = None
    #: Whether the description was written by a human, generated by a model, or
    #: derived from the profile. Governance metadata, not decoration: a
    #: `derived` description is a gap someone should fill.
    description_source: str | None = None
    unit: str | None = None
    caveat: str | None = None
    null_fraction: float
    approx_distinct: int
    sample_values: list[Any]


class CatalogResponse(BaseModel):
    version: str
    role: str
    columns: list[CatalogColumn]
    #: How many rows the columns describe, so the drawer can say what it is a
    #: catalogue *of* rather than listing names in a vacuum.
    total_rows: int


@router.get("/catalog", response_model=CatalogResponse)
async def catalog(principal: PrincipalDep, state: StateDep) -> CatalogResponse:
    scope = scope_catalog(state.catalog, principal)
    return CatalogResponse(
        version=scope.version,
        role=scope.role,
        total_rows=state.catalog.stats.row_count,
        columns=[
            CatalogColumn(
                name=column.name,
                type=column.duckdb_type,
                semantic_type=column.semantic_type.value,
                description=column.description.text if column.description else None,
                description_source=(
                    column.description.source.value if column.description else None
                ),
                unit=column.description.unit if column.description else None,
                caveat=column.description.caveat if column.description else None,
                null_fraction=column.null_fraction,
                approx_distinct=column.approx_distinct,
                sample_values=column.sample_values,
            )
            for column in scope.columns.values()
        ],
    )
